# Favicon
favicon: /favicon.ico

# SEO
keywords: "Java Python R 机器学习 统计 扯淡"

# Site title separator
separator: '-'

# RSS
# 需安装插件npm install hexo-generator-feed
rss: /atom.xml

# SNS config
sns:
  Blog: /archives

# Nav menu
menu:
  Home: /archives
  Tags: /tags
  About: /about
  RSS: /atom.xml
